services:
  # Schema migrator - runs first to set up database
  schema-migrator-sync:
    image: signoz/signoz-schema-migrator:v0.128.2
    container_name: schema-migrator-sync
    command:
      - sync
      - --dsn=tcp://signoz-clickhouse:9000
      - --up=
    depends_on:
      signoz-clickhouse:
        condition: service_healthy
    networks:
      - kafka-network
    restart: on-failure

  # SigNoz Services
  signoz-zookeeper:
    image: bitnami/zookeeper:3.7.1
    container_name: signoz-zookeeper
    user: root
    environment:
      - ZOO_SERVER_ID=1
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_AUTOPURGE_INTERVAL=1
    volumes:
      - signoz_zookeeper:/bitnami/zookeeper
    networks:
      - kafka-network
    healthcheck:
      test: ["CMD-SHELL", "curl -s -m 2 http://localhost:8080/commands/ruok | grep error | grep null"]
      interval: 30s
      timeout: 5s
      retries: 3

  signoz-clickhouse:
    image: clickhouse/clickhouse-server:24.1.2-alpine
    container_name: signoz-clickhouse
    volumes:
      - signoz_clickhouse:/var/lib/clickhouse/
      - ./deploy/signoz/clickhouse-config.xml:/etc/clickhouse-server/config.xml
    depends_on:
      - signoz-zookeeper
    networks:
      - kafka-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "0.0.0.0:8123/ping"]
      interval: 30s
      timeout: 5s
      retries: 3

  signoz:
    image: signoz/signoz:v0.91.0
    container_name: signoz
    command:
      - --config=/root/config/prometheus.yml
    ports:
      - "3301:8080"  # SigNoz UI mapped to 3301 to avoid conflict with Kafka UI
    volumes:
      - ./deploy/signoz/prometheus.yml:/root/config/prometheus.yml
      - signoz_data:/var/lib/signoz/
    environment:
      - SIGNOZ_TELEMETRYSTORE_CLICKHOUSE_DSN=tcp://signoz-clickhouse:9000
      - SIGNOZ_SQLSTORE_SQLITE_PATH=/var/lib/signoz/signoz.db
      - STORAGE=clickhouse
      - TELEMETRY_ENABLED=true
      - DEPLOYMENT_TYPE=docker-standalone-amd
      - SIGNOZ_JWT_SECRET=your-secret-key-here-change-in-production
    depends_on:
      signoz-clickhouse:
        condition: service_healthy
      schema-migrator-sync:
        condition: service_completed_successfully
    networks:
      - kafka-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "localhost:8080/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  otel-collector:
    image: signoz/signoz-otel-collector:v0.128.2
    container_name: signoz-otel-collector
    command:
      - --config=/etc/otel-collector-config.yaml
      - --feature-gates=-pkg.translator.prometheus.NormalizeName
    volumes:
      - ./deploy/signoz/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"  # OTLP gRPC receiver
      - "4318:4318"  # OTLP HTTP receiver
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=host.name=signoz-host,os.type=linux
    depends_on:
      signoz:
        condition: service_healthy
    networks:
      - kafka-network

volumes:
  signoz_zookeeper:
  signoz_clickhouse:
  signoz_data:

networks:
  kafka-network:
    external: true