- name: Deploy Kafka UI using kubectl
  shell: |
    cat <<EOF | kubectl apply -f -
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: kafka-ui
      namespace: {{ k8s_namespace }}
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: kafka-ui
      template:
        metadata:
          labels:
            app: kafka-ui
        spec:
          containers:
            - name: kafka-ui
              image: provectuslabs/kafka-ui:latest
              ports:
                - containerPort: 8080
              env:
                - name: KAFKA_CLUSTERS_0_NAME
                  value: local
                - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
                  value: kafka-service:9092
    EOF
  changed_when: false

- name: Deploy Kafka UI Service using kubectl
  shell: |
    cat <<EOF | kubectl apply -f -
    apiVersion: v1
    kind: Service
    metadata:
      name: kafka-ui-service
      namespace: {{ k8s_namespace }}
    spec:
      selector:
        app: kafka-ui
      ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
      type: NodePort
    EOF
  changed_when: false

- name: Get service information
  shell: |
    echo "Order Gateway: $(kubectl get svc order-gateway-service -n {{ k8s_namespace }} -o jsonpath='{.spec.ports[0].nodePort}' 2>/dev/null || echo 'Not ready')"
    echo "Kafka UI: $(kubectl get svc kafka-ui-service -n {{ k8s_namespace }} -o jsonpath='{.spec.ports[0].nodePort}' 2>/dev/null || echo 'Not ready')"
  register: service_info
  changed_when: false

- name: Display service URLs
  debug:
    msg:
      - '🚀 Deployment completed successfully!'
      - '📱 Access your services at http://{{ minikube_ip }}:<nodeport>'
      - '{{ service_info.stdout_lines }}'
